### ISSUE TITLE
Printing Gibberish

### ISSUE THREAD

**Issue by mjs513** [getSurreal/XV_Lidar_Controller#2]
Hi

I just finished hooking everything up - no brainer.  But when I first loaded the sketch I received a series of .pid.cpp errors (a lot of different stray characters).  If I delete those files the sketch loads fine but prints out gibberish.  There are no errors messages printed from the setup (no I didn't miss it, I added a delay just in case).  I did see one clear message about 3 ESCs or Break.  That was about it before the gibberish started - its like what you see if the baudrate is set wrong. By the way yes the baud was at 115200.

I am running IDE 1.6.7 on a windows 10 x64 laptop by the way.

thanks for your help
Mike

UPDATE:  I tried a second unit and it still has the same issues.  By the way I tried 1.3.0 as a test.

**Comment by mjs513** [comment]
Never mind - my issue - I didn't read the get started portion of the website until just now.  I am going to close this.  All distances are showing as zero.  RPM is steady around 299 - 300.

**Comment by getSurreal** [comment]
After Arduino IDE 1.6.5 compilation errors started.  Zero values 
typically indicate errors in the data.  The dev branch has some updates 
that introduces error detection.

For now use Arduino 1.6.5 with teensyduino 1.26 for best results.

**Comment by mjs513** [comment]
Thanks for the response - I swapped out the lidars and the all worked well with the sketch using 1.6.7.  Maybe I will give version 1.3 a try.  By the way - I love the card.  I am going to try and link it to an Arduino to send the data to or Teensy 3.1 do some obstacle avoidance stuff. Only thing I wish is that I had access to pins 9 and 10 so you could use altsoftserial to get another serial port.  Have you guys ever thought about using a teensy 3.1 and breaking out the serial pins?

Thanks for your help.
Mike

**Comment by getSurreal** [comment]
We do have a design for a board with a teensy 3.1/3.2, but it's still 
under heavy development so unfortunately it won't be ready any time soon.
